"""The picture a booth shows while it boots, before the application can.

Between power-on and the welcome screen a Linux host prints its kernel and
systemd messages, then shows a desktop, then a black window while the camera and
the templates load. Guests see all of it: a booth is usually switched on in the
room it stands in. Plymouth covers the first part with a theme, the desktop can
be given the same picture as its wallpaper, and the application draws its own
loading screen over that picture for the rest (libs/screens/loading.py).

This builds the Plymouth theme. It runs at install time, headless, and imports
neither Kivy nor anything that would open a window.

Plymouth knows nothing of the booth's ROTATION: it draws on the panel as the
panel is mounted. So the picture is cropped to what a guest sees and then
turned the way Kivy turns the interface, and the animation is placed in the
guest's frame and mapped back onto the panel's.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageOps

THEME_NAME = 'photobooth'

# How dark the veil laid over the welcome photo is. The application's loading
# screen uses the same one, so the picture does not change shade when it takes
# over from the splash.
VEIL_OPACITY = 0.35

# The waiting dots, in the guest's frame: centred horizontally, in the lower
# part of the picture where a welcome title is least likely to be. Sizes are
# fractions of the panel's short side, as everywhere else in the interface.
DOTS_CENTRE = (0.5, 0.8)
DOT_SIZE = 0.03
DOT_SPACING = 0.06
DOT_COUNT = 3

# Drawn once and scaled by the script: the panel's real mode is only known at
# boot, and a circle survives scaling where a pre-sized one would not.
DOT_TEXTURE_SIZE = 128


def guest_size(panel_size, rotation):
    """The picture as a guest sees it: the panel's mode, turned upright."""
    width, height = panel_size
    if rotation in (90, 270):
        return height, width
    return width, height


def to_panel_fraction(point, rotation):
    """Map a point of the guest's picture onto the panel, both as 0..1 fractions.

    Kivy turns the interface counter-clockwise by ROTATION, as does
    Image.rotate, so the same mapping serves the picture and the dots.
    """
    u, v = point
    if rotation == 90:
        return v, 1 - u
    if rotation == 180:
        return 1 - u, 1 - v
    if rotation == 270:
        return 1 - v, u
    return u, v


def guest_right_on_panel(rotation):
    """Which way along the panel a guest's "to the right" runs, as a unit vector."""
    return {0: (1, 0), 90: (0, -1), 180: (-1, 0), 270: (0, 1)}.get(rotation, (1, 0))


def render_background(source, panel_size, rotation):
    """The welcome photo, covering the guest's view, veiled and turned for the panel."""
    with Image.open(source) as photo:
        photo = ImageOps.exif_transpose(photo).convert('RGB')
        picture = ImageOps.fit(photo, guest_size(panel_size, rotation), Image.LANCZOS)
    veil = Image.new('RGB', picture.size, (0, 0, 0))
    picture = Image.blend(picture, veil, VEIL_OPACITY)
    if rotation:
        picture = picture.rotate(rotation, expand=True)
    return picture


def render_dot():
    size = DOT_TEXTURE_SIZE
    # Drawn four times larger and reduced, for an edge that is not stair-stepped.
    large = Image.new('L', (size * 4, size * 4), 0)
    ImageDraw.Draw(large).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
    mask = large.resize((size, size), Image.LANCZOS)
    dot = Image.new('RGBA', (size, size), (255, 255, 255, 0))
    dot.putalpha(mask)
    return dot


def render_script(rotation):
    centre_x, centre_y = to_panel_fraction(DOTS_CENTRE, rotation)
    step_x, step_y = guest_right_on_panel(rotation)
    return f"""\
# Generated by tools/boot_splash.py for ROTATION = {rotation}. Re-run the
# installer rather than editing it: the picture and this script go together.

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();
short_side = Math.Min(screen_width, screen_height);

# The picture already has the panel's proportions; covering rather than
# stretching keeps it undistorted when the panel runs another mode.
picture = Image("splash.png");
scale = Math.Max(screen_width / picture.GetWidth(), screen_height / picture.GetHeight());
background = Sprite(picture.Scale(picture.GetWidth() * scale, picture.GetHeight() * scale));
background.SetPosition((screen_width - picture.GetWidth() * scale) / 2,
                       (screen_height - picture.GetHeight() * scale) / 2, 0);

dot_size = short_side * {DOT_SIZE};
dot_image = Image("dot.png").Scale(dot_size, dot_size);
for (i = 0; i < {DOT_COUNT}; i++) {{
    offset = (i - ({DOT_COUNT} - 1) / 2) * short_side * {DOT_SPACING};
    dots[i] = Sprite(dot_image);
    dots[i].SetPosition(screen_width * {centre_x:g} + offset * ({step_x}) - dot_size / 2,
                        screen_height * {centre_y:g} + offset * ({step_y}) - dot_size / 2, 1);
}}

frame = 0;
fun refresh_callback() {{
    frame++;
    for (i = 0; i < {DOT_COUNT}; i++) {{
        # One wave travelling along the dots, a little over a second per pass.
        wave = (Math.Sin(frame * 0.1 - i * 0.9) + 1) / 2;
        dots[i].SetOpacity(0.3 + 0.7 * wave);
    }}
}}
Plymouth.SetRefreshFunction(refresh_callback);
"""


def render_theme_descriptor(install_directory):
    return f"""\
[Plymouth Theme]
Name=Photobooth
Description=The booth's welcome picture while it starts
ModuleName=script

[script]
ImageDir={install_directory}
ScriptFile={install_directory}/{THEME_NAME}.script
"""


def build_theme(output_directory, install_directory, source, panel_size, rotation):
    """Write the theme's files into output_directory; returns their paths.

    install_directory is where they will live once installed, which the
    descriptor has to name: Plymouth does not look for them next to itself.
    """
    output = Path(output_directory)
    output.mkdir(parents=True, exist_ok=True)

    paths = {
        'splash': output / 'splash.png',
        'dot': output / 'dot.png',
        'script': output / f'{THEME_NAME}.script',
        'descriptor': output / f'{THEME_NAME}.plymouth',
    }
    # PNG only: Plymouth's image loader reads nothing else.
    render_background(source, panel_size, rotation).save(paths['splash'], optimize=True)
    render_dot().save(paths['dot'])
    paths['script'].write_bytes(render_script(rotation).encode('utf-8'))
    paths['descriptor'].write_bytes(render_theme_descriptor(install_directory).encode('utf-8'))
    return paths
